config/routes.rb
# frozen_string_literal: true

# settings for different routes used in app
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    profiles: 'users/profiles'
  }

  authenticate :user do
    resources :channels, only: %i[edit update destroy create new]
    resources :videos, only: %i[edit update destroy create new]
  end

  resources :channels, only: %i[index show]
  resources :videos, only: %i[index show]
  resources :videos do
    get :autocomplete_video_title, on: :collection, as: :ac_vid
  end


  scope '/fav', controllers: '' do
    get '', to: 'favorites#list', as: :favlist
    get '/:uid', to:'favorites#view', as: :u_fav
  end

  scope '/:username',controllers: '' do
    get '', to: 'users/profiles#show', as: :profile
    get '/favorites/edit', to: 'favorites#edit_all', as: :edit_my_favorites
    resources :favorites
  end


  get '/channels/show_iframe/:id', to: 'channels#show_iframe',
                                   as: :channels_iframe

  root to: 'home#index'
  get '*path', to: redirect('/'), message: 'Invalid url or unauthorized'
end
    

app/models/channel.rb
# frozen_string_literal: true
#  create_table 'channels', force: :cascade do |t|
#    t.string 'name'
#    t.string 'channel_url'
#    t.datetime 'created_at', null: false
#    t.datetime 'updated_at', null: false
#    t.string 'youtube_id'
#  end
# channel model

class Channel < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3 }
  validates :channel_url, presence: true
  validates :youtube_id, uniqueness: true
  has_many :videos, dependent: :destroy
  has_many :favorites, dependent: :destroy

  after_initialize :make_params_from_id, if: :new_record?

  def make_params_from_id
    unless self.youtube_id.nil?
      yt_obj = Yt::Channel.new id: self.youtube_id
      self.channel_url = 'https://www.youtube.com/' + yt_obj.title
      self.name = yt_obj.title
    end
  end

  def videos_as_yt_objs
    arr = []
    self.videos.each do |v|
      x = Yt::Video.new id: v.youtube_id
      arr << x
    end
    arr
  end
end

app/controllers/channels_controller.rb
# frozen_string_literal: true

# defined CRUD operations for manipulating data from the DB and from the views
# also extra show as iframe for the embedded view
class ChannelsController < ApplicationController
  before_action :authenticate_user!, only: %i[create new edit destroy]

  def index
    @channels = Channel.all.paginate(page: params[:page], per_page: 10)
  end

  def new
    @channel = Channel.new
    @videos = Video.all
  end

  def create
    @channel = Channel.new(youtube_id: channel_params[:youtube_id])
    append_vids(channel_params[:videos]) unless channel_params[:videos].nil?
    if @channel.save
      redirect_to @channel
    else
      render 'new'
    end
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update(channel_params)
      redirect_to channels_path(@channel)
    else
      render 'edit'
    end
  end

  def destroy
    Channel.find(params[:id]).destroy
    flash[:success] = 'Channel deleted succesfully'
    redirect_to channels_url
  end

  def edit
    @channel = Channel.find(params[:id])
    @videos = Video.all
  end

  def show
    @channel = Channel.find(params[:id])
    @videos = Video.where(channel_id: @channel.id)
    @videos = @videos.paginate(page: params[:page], per_page:40)
  end

  def show_iframe
    @channel = Channel.find(params[:id])
    @videos = @channel.videos.paginate(page: params[:page], per_page: 5)
    @yt_objs = []
    @videos.each do |v|
      x = Yt::Video.new id: v.youtube_id
      @yt_objs << x
    end
  end

  private

  def append_vids(vids)
    vids.each { |vid| @channel.videos.append(Video.find(vid)) }
  end

  def channel_params
    params.require(:channel).permit(:name,
                                    :channel_url,
                                    :youtube_id,
                                    videos: [])
  end
end

app/views/channels/_form.html.erb
<%= form_with(model: channel, local: true) do |form| %>
  <% if channel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(channel.errors.count, "error") %> prohibited this channel from being saved:</h2>

      <ul>
      <% channel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<div class='row justify-content-center'>

	<div class='col-6'>
		<h1 style='text-align: center'>Editing Channel</h1>
<div class = "form-group">
<%= simple_form_for @channel do |data| %>
	<%= data.input :name, input_html:{class: 'form-control'}%>
	<%= data.input :channel_url, input_html:{class: 'form-control'} %>
	<br>
	<%= data.button :submit, class: 'btn btn-primary btn-block' %>
	<br>
<%end%>
<%= button_to 'Back', channels_path, method: :get, class: 'btn btn-danger btn-block' %>
</div>
</div>
</div>

app/views/channels/index.html.erb
<h1 class='typography-display-3 text-center'>
  Channels
 <p id="notice" class='txt-primary'><%= notice %></p>
</h1>

<table class='table table-striped table-bordered'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>#</th>
      <th scope='col'>Channel Title</th>
      <th scope='col'>Channel URL</th>
      <th scope='col'>View</th>
      <th scope='col'>Modify</th>
      <th scope='col'>Remove</th>
    </tr>
  </thead>
  <tbody>
    <% @channels.each do |channel| %>
      <tr>
        <td><%= channel.id %></td>
        <td><%= link_to channel.name,channels_iframe_path(channel.id)%></td>
        <td><%= channel.channel_url%></td>
        <td><%= button_to 'Show', channel_path(channel), method: :get, class: 'btn btn-info btn-block' %></td>
        <td><%= button_to 'Edit', edit_channel_path(channel), method: :get, class: 'btn btn-secondary btn-block' %></td>
        <td><%= button_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'New Channel', new_channel_path, method: :get, class: 'btn btn-primary btn-block' %>
<br>
<div class='row justify-content-center'>
  <%= will_paginate %>
</div>

app/views/channels/new.html.erb
<div class='row justify-content-center'>
	<div class='col-6'>
		<h1 style='text-align: center' >New Channel</h1>
		<div class = "form-group">
			<%= simple_form_for @channel do |data| %>
			<%= data.input :youtube_id, input_html: {class: 'form-control'} %>
			<br>
			<%= data.button :submit, class: 'btn-primary btn btn-block' %>
			<%end%>
			<br>
			<%= button_to 'Back', channels_path, method: :get, class: 'btn btn-danger btn-block' %>
			<br>
			<div class='text-danger text-center font-weight-bold'>
				<%= @errors unless @errors.nil? %>
			</div>
		</div>
	</div>
</div>

app/views/channels/show.html.erb
<p id="notice"><%= notice %></p>
<div class='row justify-content-center'>
	<div class='col-6' align='center'>
		<div class='card'>
			<div class='card-title'>
				<p style='padding-top: 2rem'> Channel Name : <%= @channel.name %> </p>
				<p> Channel URL :<a href=<%=@channel.channel_url%>> <%= @channel.channel_url %></a> </p>
			</div>
			<div class='card-body'>
				<% @videos.where(channel_id: @channel.id).each do |vid| %>
				<ul style ="padding:0; list-style-type: none;">
					<li><%= link_to vid.title, video_path(vid)%></li>
					<%end%>	
				</ul>
				<div class='row justify-content-center'>
				<%= will_paginate(@videos) %>
			</div>
			</div>
		</div>
		<%= button_to 'Edit', edit_channel_path(@channel),method: :get, class: 'btn btn-secondary btn-block' %>
		<br>
		<%= button_to 'Back', channels_path, method: :get, class: 'btn btn-info btn-block' %>
	</div>
</div>

app/views/channels/show_iframe.html.erb
<p id="notice"><%= notice %></p>

<div class='row justify-content-center'>
	<div class='col-6' align='center'>
		<div class='card'>
			<div class='card-title'>
				<p style='padding-top: 2rem'> Channel Name : <%= @channel.name %> </p>
				<p> Channel URL :<a href=<%=@channel.channel_url%>> <%= @channel.channel_url %></a> </p>
			</div>
			<div class='card-body'>
				<p> Videos : <% @yt_objs.each do |vid| %>
					<ul style ="padding:0; list-style-type: none;">
						<li class='embed-responsive embed-responsive-16by9'>
							<%= vid.embed_html.html_safe%>
						</li>
						<%end%>	
					</ul>
				</p>
				<%= button_to 'Back', channels_path, method: :get, class: 'btn btn-danger btn-block' %>
			</div>
		</div>
	</div>
</div>
<div class='row justify-content-center'>
	<%= will_paginate @videos%>
</div>