config/routes.rb
# frozen_string_literal: true

# settings for different routes used in app
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    profiles: 'users/profiles'
  }

  authenticate :user do
    resources :channels, only: %i[edit update destroy create new]
    resources :videos, only: %i[edit update destroy create new]
  end

  resources :channels, only: %i[index show]
  resources :videos, only: %i[index show]
  resources :videos do
    get :autocomplete_video_title, on: :collection, as: :ac_vid
  end


  scope '/fav', controllers: '' do
    get '', to: 'favorites#list', as: :favlist
    get '/:uid', to:'favorites#view', as: :u_fav
  end

  scope '/:username',controllers: '' do
    get '', to: 'users/profiles#show', as: :profile
    get '/favorites/edit', to: 'favorites#edit_all', as: :edit_my_favorites
    resources :favorites
  end


  get '/channels/show_iframe/:id', to: 'channels#show_iframe',
                                   as: :channels_iframe

  root to: 'home#index'
  get '*path', to: redirect('/'), message: 'Invalid url or unauthorized'
end
    

app/models/favorite.rb
# frozen_string_literal: true

# model is actually just linking 2 other models
class Favorite < ApplicationRecord
  belongs_to :user, optional: false
  belongs_to :channel, optional: true
  belongs_to :video, optional: true
  #validates :user_id, uniqueness: { scope: :channel_id, message: 'Cannot have same channel favorited twice', allow_nil: true, allow_blank: true}
  validate :unique_not_nil
  validate :is_dupe?
  validates_uniqueness_of :video_id, scope: :user_id

  private

  def is_dupe?
    unless self.video_id.nil?
      vid = Video.find(self.video_id)
      ch = vid.channel_id
      uids = Favorite.where(channel_id: ch).pluck('user_id')
      if uids.include?(self.user_id.to_s)
        @errors.add(:video_id, 'already exists in some form')
      end
    end
  end

  def unique_not_nil
    unless self.channel_id.nil?
      if Favorite.where(user_id: self.user_id).pluck('channel_id').include?(self.channel_id.to_s)
        @errors.add(:user_id, 'can\'t favorite same channel twice')
      end
    end
  end
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

# defines methods used by users who are signed in
# so that only them can view favorite channels
class FavoritesController < ApplicationController
  before_action :check_user
  
  def autocomplete_videos
    @videos = Video.all
    respond_to do |format|
      format.json { render json: @videos.to_json }
    end
  end

  def index
    action :authenticate_user! unless user_signed_in?
    vdids = Favorite.where(user_id: current_user.id).pluck(:video_id)
    chids = Favorite.where(user_id: current_user.id).pluck(:channel_id)
    @videos = Video.where(channel_id: chids).or(Video.where(id: vdids))
    @videos = @videos.paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.json {render json:@videos}
    end
  end

  def list
    @all_favs = Hash.new
    User.where.not(id: current_user.id).each do |u|
      @all_favs[u.id] = Favorite.where(user_id: u.id)
    end
  end

  def view
    @user_favs = Video.where(channel_id: Favorite.where(user_id: params[:uid]).pluck(:channel_id)).or(
                 Video.where(id: Favorite.where(user_id: params[:uid]).pluck(:video_id))).
                 paginate(page: params[:page], per_page: 10)
  end

  def new
    @favorite = Favorite.new
    @v = Video.pluck(:id,:title)
    render 'new'
  end

  def destroy
    Favorite.find(users_params[:id]).destroy
  end

  def edit_all
    @favs = Favorite.where(user_id: current_user.id)
    render 'edit'
  end

  def create
    puts params[:video_id]
    @favorite = Favorite.new(channel_id: users_params[:channel_id],
                          video_id: users_params[:video_id],
                          user_id: current_user.id)
    check_save
  end

  private

  def users_params
    params.require(:favorite).permit(:channel_id, :video_title, :video_id, :uid)
  end

  def check_user
    unless params[:username].nil?
      unless current_user.username == params[:username]
        flash[:notice] = 'You cannot modify other user\'s favorites'
        redirect_to root_url
      end
    end
  end

  def check_save
    unless @favorite.errors.any?
      redirect_to favorites_path
    else
      @channels = Channel.all
      @errors = @favorite.errors
      render :new
    end
  end
end

app/views/favorites/edit.html.erb
<table class='table table-striped table-bordered'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>Channel Name</th>
      <th scope='col'>Video Name</th>
      <th scope='col'>Remove Favorite</th>
    </tr>
  </thead>

  <tbody>
    <% @favs.each do |f| %>
      <tr>
        <td><%= unless f.channel_id.blank? then Channel.find(f.channel_id).name end %></td>
        <td><%= unless f.video_id.blank? then Video.find(f.video_id).title end%></td>
        <td><%= button_to 'Destroy', favorites_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/favorites/index.html.erb
<body>
	<% if @videos.empty? %>
	<h1 style='text-align: center'> It seems you haven't added any videos yet </h1>
	<h1 style='text-align: center'> Click <a href=<%=new_favorite_path%>>here </a> to add a favorite channel </h1>
	<% end %>
	<% if user_signed_in? %>
	<ul style ="padding:0; list-style-type: none;">
		<% @videos.each_slice(5) do |v| %>
		<div class ='row'>
			<%v.each do |yt_vid| %>
			<% yt_obj = Yt::Video.new id: yt_vid.youtube_id %>
			<div class='col'>
				<div class='card'>
					<div class='card-body embed-responsive-16by9 embed-responsive'>
						<%= yt_obj.embed_html.html_safe %>
					</div>
				</div>
				<div class='card'>
					<div class='card-body'>
						<%= simple_format(yt_obj.description).gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
		<%end%>	
	</ul>
	<%end%>
<div class='row justify-content-center'>
	<%= will_paginate @videos%>
</div>
<% console %>
</body>

app/views/favorites/list.html.erb
<div class='row justify-content-center'>
	<div class='row'>
		<% @all_favs.each do |(id,favs)| %>
		<div class='card'>
			<div class='card-body'>
				<div class='card-text'>
					<%= User.find(id).username %>
					<br>
					<%= link_to "Favorites of this user",u_fav_path(id) %>
				</div>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/favorites/new.html.erb
<div class='row justify-content-center'>
	<div class='col-6'>
		<%= if(@message) then @message end%>
		<% if !@errors.nil? %>
		<% @errors.full_messages.each do |msg| %>
		<p> <%= msg %> </p>
		<% end %>
		<% end %>
		<div class='form-group'>
			<%= simple_form_for @favorite do |data| %>
				<%= data.input :video_id, collection: @v, input_html: {class: 'form-control'},label_method: :second, value_method: :first %>
<!-- 			  <%= data.input :video_id, as: :autocomplete, source: @v, input_html: {class: 'form-control'}%>
 -->			  <br>
			  <%= data.input :channel_id, input_html: {class: 'form-control'}%>
			  <br>
			  <%= data.button :submit, class: 'btn btn-block btn-info' %>
			<%end%>
		</div>
	</div>
</div>


<script>
	var vinput = $('#favorite_video_id');
	var chinput = $('#favorite_channel_id');

	vinput.change(function(){
		if($(this).val() != ""){
			chinput.val("");
			chinput.prop('placeholder','Add either a single video or whole channel');
			chinput.prop('disabled',true);
		}
		else{
			chinput.prop('placeholder','');
			chinput.prop('disabled',false);
		}
	});

	chinput.change(function(){
		if($(this).val() != ""){
			vinput.val("");
			vinput.prop('placeholder','Add either a single video or whole channel');
			vinput.prop('disabled',true);
		}
		else{
			vinput.prop('placeholder','');
			vinput.prop('disabled',false);
		}
	});
</script>

app/views/favorites/view.html.erb
<body>
	<% if @user_favs.empty? %>
	<h1 style='text-align: center'> It seems this user hasn't added any videos yet </h1>
	<% end %>
	<ul style ="padding:0; list-style-type: none;">
		<% @user_favs.each_slice(5) do |v| %>
		<div class ='row'>
			<% v.each do |yt_vid| %>
			<% yt_obj = Yt::Video.new id: yt_vid.youtube_id %>
			<div class='col'>
				<div class='card'>
					<div class='card-body embed-responsive-16by9 embed-responsive'>
						<%= yt_obj.embed_html.html_safe %>
					</div>
				</div>
				<div class='card'>
					<div class='card-body'>
						<%= simple_format(yt_obj.description).gsub(URI.regexp, '<a href="\0">\0</a>').html_safe %>
					</div>
				</div>
			</div>
			<% end %>
		</div>
		<%end%>	
	</ul>
<div class='row justify-content-center'>
	<%= will_paginate @user_favs%>
</div>

</body>