config/routes.rb
# frozen_string_literal: true

# settings for different routes used in app
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    profiles: 'users/profiles'
  }

  authenticate :user do
    resources :channels, only: %i[edit update destroy create new]
    resources :videos, only: %i[edit update destroy create new]
  end

  resources :channels, only: %i[index show]
  resources :videos, only: %i[index show]
  resources :videos do
    get :autocomplete_video_title, on: :collection, as: :ac_vid
  end


  scope '/fav', controllers: '' do
    get '', to: 'favorites#list', as: :favlist
    get '/:uid', to:'favorites#view', as: :u_fav
  end

  scope '/:username',controllers: '' do
    get '', to: 'users/profiles#show', as: :profile
    get '/favorites/edit', to: 'favorites#edit_all', as: :edit_my_favorites
    resources :favorites
  end


  get '/channels/show_iframe/:id', to: 'channels#show_iframe',
                                   as: :channels_iframe

  root to: 'home#index'
  get '*path', to: redirect('/'), message: 'Invalid url or unauthorized'
end
    

app/models/video.rb
# frozen_string_literal: true

# video model
class Video < ApplicationRecord
  validates :channel_id, presence: true
  validates :title, presence: true
  validates :url, presence: true
  validates :youtube_id, uniqueness: true, presence: true
  belongs_to :channel, optional: true
  has_many :favorites, dependent: :destroy

  after_initialize :make_params_from_id, if: :new_record?

  def make_params_from_id
    unless self.youtube_id.nil?
      yt_vid = Yt::Video.new id:self.youtube_id
      self.title = yt_vid.title
      self.url = 'https://www.youtube.com/watch?v=' + yt_vid.id
      self.duration = yt_vid.length
      self.is_hd = yt_vid.hd?
    end
  end
end

app/controllers/videos_controller.rb
# frozen_string_literal: true

# defines crud operations for the Video model
class VideosController < ApplicationController
  def index
    @videos = Video.all.paginate(page: params[:page], per_page: 10)
  end

  def show
    @video = Video.find(params[:id])
    @yt_obj = Yt::Video.new id:@video.youtube_id
  end

  def create
    @video = Video.new(youtube_id: video_params[:youtube_id], channel_id: video_params[:channel_id])
    @channels = Channel.all
    if @video.save!
      redirect_to video_path(Video.last)
    else
      render 'new'
    end
  end

  def update
    @video = Video.find(params[:id])
    if @video.update(video_params)
      redirect_to video_path(@video)
    else
      render 'new'
    end
  end

  def edit
    @video = Video.find(params[:id])
    @channels = Channel.all
  end

  def destroy
    Video.find(params[:id]).destroy
    flash[:success] = 'Video succesfully deleted'
    redirect_to videos_url
  end

  def new
    @video = Video.new
    @channels = Channel.all
  end

  private

  def video_params
    params.require(:video).permit(:title,
                                  :url,
                                  :duration,
                                  :channel_id,
                                  :youtube_id)
  end

end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class='row justify-content-center'>
	<div class='col-6'>
		<h1 style='text-align: center'>Editing Video</h1>
		<div class='form-group'>
			<%= simple_form_for @video do |data| %>
			<%= data.input :title, input_html: {class: 'form-control'}%>
			<%= data.input :url, input_html: {class: 'form-control'}%>
			<%= data.input :duration, input_html: {class: 'form-control'}%>
			<br>
			<%= data.select(:channel_id, @channels.collect {|ch| [ch.name, ch.id]},{},{class: 'form-control'}) -%>
			<br>
			<%= data.button :submit, class: 'btn btn-primary btn-block' %>
			<%end%>
		</div>
		<%= button_to 'Back', videos_path, method: :get, class: 'btn btn-danger btn-block' %>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>
<h1 class='typography-display-3 text-center'>
  Videos
</h1>
<table class='table table-striped table-bordered'>
  <thead class='thead-dark'>
    <tr>
      <th scope='col'>#</th>
      <th scope='col'>Video Title</th>
      <th scope='col'>Video URL</th>
      <th scope='col'>View</th>
      <th scope='col'>Modify</th>
      <th scope='col'>Remove</th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.id%></td>
        <td><%= video.title%></td>
        <td><%= video.url%></td>
        <td><%= button_to 'Show', video_path(video), method: :get, class: 'btn btn-info btn-block' %></td>
        <td><%= button_to 'Edit', edit_video_path(video), method: :get, class: 'btn btn-secondary btn-block' %></td>
        <td><%= button_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-block' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= button_to 'New Video',new_video_path, method: :get, class: 'btn btn-primary btn-block' %>
<br>
<div class='row justify-content-center'>
  <%= will_paginate %>
</div>

app/views/videos/new.html.erb
<div class='row justify-content-center'>
	<div class='col-6'>
		<h1 style='text-align: center'>New Video</h1>
		<div class='form-group'>
			<%= simple_form_for @video do |data| %>
			<%= data.input :youtube_id, input_html: {class: 'form-control'} %>
			<br>
			<%= data.select(:channel_id, @channels.collect {|ch| [ch.name, ch.id]},{}, {class: 'form-control'})%>
			<br>
			<%= data.button :submit, class: 'btn btn-primary btn-block' %>
			<%end%>
		</div>
		<%= button_to 'Back', videos_path, method: :get, class: 'btn btn-danger btn-block' %>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>
<div class='row'>
	<div class='col' align='center'>
		<div class='card' style='width: 32rem'>
			<ul class='list-group'>
				<li class='list-group-item d-flex justify-content-between align-items-center'>
					Video Name : <%= @video.title %>
				</li>
				<li class='list-group-item d-flex justify-content-between align-items-center'>
					Video URL : <%= @video.url %>
				</li>
				<li class='list-group-item d-flex justify-content-between align-items-center'>
					Video Length : <%=@video.duration %>
				</li>
				<li class='list-group-item d-flex justify-content-between align-items-center'> 
					Channel : <%= link_to @video.channel.name, channel_path(@video.channel) %>
				</li>
			</ul>
		</div>
	</div>
	<div class='col'>
		<div class='card' style='width: 32rem'>
			<div class='embed-resposive embed-responsive-16by9 card-body'>
			 <%= @yt_obj.embed_html.html_safe%>
			 <div align='center'>
				 <%= button_to 'Edit', edit_video_path(@video), method: :get, class: 'btn btn-primary btn-block' %>
				 <br>
				 <%= button_to 'Back', videos_path, method: :get, class: 'btn btn-primary btn-block' %>
			 </div>
			</div>
		</div>
	</div>
</div>