config/routes.rb
# frozen_string_literal: true

# settings for different routes used in app
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    sessions: 'users/sessions',
    unlocks: 'users/unlocks',
    profiles: 'users/profiles'
  }

  authenticate :user do
    resources :channels, only: %i[edit update destroy create new]
    resources :videos, only: %i[edit update destroy create new]
  end

  resources :channels, only: %i[index show]
  resources :videos, only: %i[index show]
  resources :videos do
    get :autocomplete_video_title, on: :collection, as: :ac_vid
  end


  scope '/fav', controllers: '' do
    get '', to: 'favorites#list', as: :favlist
    get '/:uid', to:'favorites#view', as: :u_fav
  end

  scope '/:username',controllers: '' do
    get '', to: 'users/profiles#show', as: :profile
    get '/favorites/edit', to: 'favorites#edit_all', as: :edit_my_favorites
    resources :favorites
  end


  get '/channels/show_iframe/:id', to: 'channels#show_iframe',
                                   as: :channels_iframe

  root to: 'home#index'
  get '*path', to: redirect('/'), message: 'Invalid url or unauthorized'
end
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YouMimic</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel='shortcut icon' href=<%=image_path('favico.png')%> >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= yield :top_content %>
<div class="container">
  <h1><%= yield :header%></h1>
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav mr-2">
      <% if user_signed_in? %>
      <i class='material-icons align-middle'>recent_actors</i>

      <li class="nav-item">
        <%= link_to 'Channels Table',channels_path, class: 'txt-primary' %>&nbsp
      </li>

      <i class='material-icons align-middle'>video_library</i>
      <li class="nav-item">
        <%= link_to 'Videos Table', videos_path, class: 'txt-primary' %>&nbsp
      </li>

      <i class='material-icons align-middle'>folder</i>
      <li class="nav-item">
        <%= link_to 'Home' , root_path, class: 'txt-primary' %>&nbsp
      </li>

      <i class='material-icons align-middle'>favorite</i>
      <li class="nav-item">
        <%= link_to 'My Favorites', favorites_path(current_user.username), class: 'txt-primary'%>&nbsp
      </li>

      <i class='material-icons align-middle'>create</i>
      <li class="nav-item">
        <%= link_to 'New Favorite',new_favorite_path(current_user.username), class: 'txt-primary'%>&nbsp
      </li>

      <i class='material-icons align-middle'>filter_list</i>
      <li class="nav-item">
        <%= link_to 'Edit Favorites',edit_my_favorites_path(current_user.username), class: 'txt-primary'%>&nbsp
      </li>

      <li class='nav-item'>
        <i class='material-icons align-middle'>face</i>
        <%= link_to 'All favorites', favlist_path, class: 'txt-primary'%>
      </li>

      <% else %>
      <i class='material-icons align-middle'>recent_actors</i>

      <li class="nav-item">
        <%= link_to 'Channels' , channels_path, class: 'txt-primary' %>&nbsp
      </li>

      <i class='material-icons align-middle'>video_library</i>
      <li class="nav-item">
        <%= link_to 'Videos' , videos_path, class: 'txt-primary'%>&nbsp
      </li>

      <i class='material-icons align-middle'>folder</i>
      <li class="nav-item">
        <%= link_to 'Home' , root_path, class: 'txt-primary'%>&nbsp
      </li>

      <li class='nav-item'>
        <i class='material-icons align-middle'>face</i>
        <%= link_to favlist_path, class: 'txt-primary'%>
      </li>

      <% end %>
    </ul>
  </div>
  <ul class="navbar-nav pull-right">
    <% if user_signed_in? %>

    <i class='material-icons align-middle'>mood_bad</i>
    <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'txt-primary' %>&nbsp
    </li>

    <li class='nav-item'>
      <i class='material-icons align-middle'>create</i>
      <%= link_to 'Edit Account', edit_user_registration_path, class: 'txt-primary'%> &nbsp
    </li>

    <li class="nav-item">
      <i class='material-icons align-middle'>face</i>
      <%= link_to current_user.username, profile_path(current_user.username) %>
      
    </li>



    <% else %>

    <i class='material-icons align-middle'>input</i>&nbsp
    <li>
      <%= link_to 'Log In', new_user_session_path, method: :get, class: 'txt-primary' %>&nbsp
    </li>

    <i class='material-icons align-middle'>perm_identity</i>
    <li>
      <%= link_to 'Sign Up', new_user_registration_path, method: :get, class: 'txt-primary' %>
    </li>
    <% end %>
  </ul>
</nav>
<div class='progress'>
  <div class='progress-bar bg-danger' style='width: 100%'aria-valuenow='100' aria-valuemin='100' aria-valumemax='100'></div>
</div>
<body class="bg-light">
  <div style='padding-top: 3rem'>
    <%= yield %>
  </div>
</body>
<div class="container">
  <div class='row justify-content-center'>
    <% flash.each do |key,value| %>
    <div class="alert alert-<%= key%>">
     <h2><%= value %></h2>
   </div>
   <% end %>
 </div>
</div>
</html>